environment:
  matrix:
    - TARGET: 1.28.0-x86_64-pc-windows
      COMPILER: msvc
install:
  - git submodule update --init --recursive
  - if %COMPILER%==gnu choco install -y mingw
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}-${env:COMPILER}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin;C:\tools\mingw64\bin"
  - if %COMPILER%==gnu gcc -v
  - rustc -vV
  - cargo -vV
build_script:
  - cargo build --manifest-path ash/Cargo.toml
  - cargo build --manifest-path examples/Cargo.toml
